# https://taskfile.dev

version: "3"


env:
    CGO_ENABLED: 0

tasks:
    default:
        cmds:
            - task: generate
            - task: build
    build:
        cmds:
            - go build
    generate:
        cmds:
            - go generate ./...
    test:
        cmds:
            - go test -timeout 30s -v ./...
    docker-image:
        cmds:
            - docker build -f develop/Dockerfile.yaml -t cognito-sidecar:latest .
    docker-run:
        deps: [docker-image]
        cmds:
            - docker run -p 8081:8081  cognito-sidecar
    set-up:
        cmds:
            - go install github.com/cosmtrek/air@latest
    make-ddbb-image:
        cmds:
            - docker build --no-cache --tag postgress-dev:latest develop/ddbb/
    db-up:
        deps: [make-ddbb-image]
        cmds:
            - docker stop ddbb-dev || true && docker rm ddbb-dev || true
            - docker run -d -p 5432:5432 --name ddbb-dev postgress-dev
    air:
        cmds:
            - $(go env GOPATH)/bin/air --build.cmd "task build && sleep 3" --build.bin "./truckvault -conf develop/config.toml"
