# https://taskfile.dev

version: "3"


env:
    CGO_ENABLED: 0

tasks:
    default:
        cmds:
            - task: generate
            - task: build
    build:
        cmds:
            - go build
    generate:
        cmds:
            - go generate ./...
    test:
        cmds:
            - go test -timeout 30s -v ./...
    docker-image:
        cmds:
            - docker build --tag baseapi:latest -f ./build/package/Dockerfile.multistage  .
    docker-run:
        deps: [docker-image]
        cmds:
            - docker run -p 8081:8081  cognito-sidecar
    set-up:
        cmds:
            - go install github.com/cosmtrek/air@latest
    air:
        cmds:
            - $(go env GOPATH)/bin/air --build.cmd "task build && sleep 3" --build.bin "./truckvault -conf develop/config.toml"
