openapi: 3.0.0
info:
    version: 0.1.0
    title: truckvault
      
paths:
    /alive:
        get:
            responses:
                "200":                   
                    description: "asd data from station in time period"
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Alive"
                "500":
                    description: "Default error sample response"
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"


components:
    schemas:
        Error:
            type: object
            required:
                - code
                - message
            properties:
                code:
                    type: integer
                message:
                    type: string
        Alive:
            type: object
            required:
                - status
                - timestamp
            properties:
                status:
                    type: string
                timestamp:
                    type: string
                    format: date-time
